'use strict';

Object.defineProperty(exports, "__esModule", { value: true });
exports.firstNames = void 0;
/**
 * @see https://www.ef.com/wwen/english-resources/english-names/
 */
const firstNames = [
    "Oliver",
    "Jack",
    "Harry",
    "Jacob",
    "Charlie",
    "Thomas",
    "George",
    "Oscar",
    "James",
    "William",
    "Jake",
    "Connor",
    "Callum",
    "Kyle",
    "Joe",
    "Reece",
    "Rhys",
    "Damian",
    "Noah",
    "Liam",
    "Mason",
    "Ethan",
    "Michael",
    "Alexander",
    "Daniel",
    "John",
    "Robert",
    "Richard",
    "Joseph",
    "Charles",
    "Amelia",
    "Olivia",
    "Isla",
    "Emily",
    "Poppy",
    "Ava",
    "Isabella",
    "Jessica",
    "Lily",
    "Sophie",
    "Margaret",
    "Samantha",
    "Bethany",
    "Elizabeth",
    "Joanne",
    "Megan",
    "Victoria",
    "Lauren",
    "Michelle",
    "Tracy",
    "Emma",
    "Sophia",
    "Mia",
    "Abigail",
    "Madison",
    "Charlotte",
    "Mary",
    "Patricia",
    "Jennifer",
    "Linda",
    "Barbara",
    "Susan",
    "Sarah",
];
exports.firstNames = firstNames;
